# Generated by Django 5.1 on 2024-08-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_admin_name',
        ),
        migrations.AddField(
            model_name='school',
            name='school_admin_first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_admin_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
