# Generated by Django 5.1 on 2024-08-16 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_school_school_admin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacher_model',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher_model',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher_Model',
        ),
    ]
