# Generated by Django 5.1 on 2024-08-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
