# Generated by Django 5.1 on 2024-08-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Peon', 'Peon'), ('Security', 'Security'), ('Warden', 'Warden'), ('Office Staff', 'Office Staff')], default='Teacher', max_length=20),
        ),
    ]
