# Generated by Django 5.1 on 2024-08-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_student_m_alter_attendance_student_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student_m',
        ),
    ]
