# Generated by Django 5.1 on 2024-08-16 10:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_student_attendance_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel_Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_assigned', models.CharField(max_length=20)),
                ('division_assigned', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.student')),
            ],
        ),
    ]
