# Generated by Django 5.1 on 2024-08-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_hostel_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_teacher',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='class_teacher',
            name='school',
        ),
        migrations.RemoveField(
            model_name='class_teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='school',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='hostel_attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='warden',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='school',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Class_Teacher',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Hostel_Attendance',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Warden',
        ),
    ]
