# Generated by Django 5.1 on 2024-08-17 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_teacher',
            name='employee',
        ),
        migrations.AddField(
            model_name='class_teacher',
            name='Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.teacher'),
        ),
    ]
