# Generated by Django 5.1 on 2024-08-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_remove_class_teacher_employee_class_teacher_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
