# Generated by Django 5.1 on 2024-08-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0032_teacher_contact_number_warden_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_class_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
