# Generated by Django 5.1 on 2024-08-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0035_class_teacher_user_name_employee_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
