# Generated by Django 5.1 on 2024-08-20 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0037_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('class_assigned', models.CharField(max_length=20)),
                ('division_assigned', models.CharField(max_length=10)),
                ('exam_name', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('class_assigned', models.CharField(max_length=20)),
                ('division_assigned', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=255)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_assigned', models.CharField(max_length=20)),
                ('division_assigned', models.CharField(max_length=10)),
                ('marks_obtained', models.FloatField(blank=True, null=True)),
                ('out_of', models.FloatField(blank=True, null=True)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.subject')),
            ],
        ),
    ]
