# Generated by Django 5.1 on 2024-08-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0038_exam_subject_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks_obtained',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='out_of',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
