# Generated by Django 5.1 on 2024-08-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0039_alter_marks_marks_obtained_alter_marks_out_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parents_email',
            field=models.EmailField(max_length=40, null=True),
        ),
    ]
